# Generated by Django 3.1 on 2020-08-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Math problem', 'Math problem'), ('Computer program', 'Computer program'), ('English', 'English'), ('Science', 'Science')], max_length=20)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='media')),
                ('email', models.EmailField(max_length=50, verbose_name='Email Address')),
            ],
        ),
    ]
